name: nail_ed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_storage: ^12.4.5
  table_calendar: ^3.0.8
  firebase_app_check: ^0.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_nailed.png"
  web:
    generate: true           #genera los iconos PWA/web en /web/icons
  windows:
    generate: true           # genera iconos para Windows
    image_path: "assets/icon_nailed.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon_nailed.png
