// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNMcAX69F21sIcGK7117jSqJdwvAOaOQ',
    appId: '1:229424533122:web:2a82c5d7d7299aab8d2e9b',
    messagingSenderId: '229424533122',
    projectId: 'nail-ed',
    authDomain: 'nail-ed.firebaseapp.com',
    storageBucket: 'nail-ed.firebasestorage.app',
    measurementId: 'G-62Q8M0T3W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ro-_HX_1NJgGpausxfEVRylNXTQ7TCk',
    appId: '1:229424533122:android:5e3be5de474801018d2e9b',
    messagingSenderId: '229424533122',
    projectId: 'nail-ed',
    storageBucket: 'nail-ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRcn0N5yUMIXAKXZABvIZ-BlBdD4YUho',
    appId: '1:229424533122:ios:8c1acb59d9711c0d8d2e9b',
    messagingSenderId: '229424533122',
    projectId: 'nail-ed',
    storageBucket: 'nail-ed.firebasestorage.app',
    iosBundleId: 'com.example.nailAppFronted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRcn0N5yUMIXAKXZABvIZ-BlBdD4YUho',
    appId: '1:229424533122:ios:8c1acb59d9711c0d8d2e9b',
    messagingSenderId: '229424533122',
    projectId: 'nail-ed',
    storageBucket: 'nail-ed.firebasestorage.app',
    iosBundleId: 'com.example.nailAppFronted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNMcAX69F21sIcGK7117jSqJdwvAOaOQ',
    appId: '1:229424533122:web:2a82c5d7d7299aab8d2e9b',
    messagingSenderId: '229424533122',
    projectId: 'nail-ed',
    authDomain: 'nail-ed.firebaseapp.com',
    storageBucket: 'nail-ed.firebasestorage.app',
    measurementId: 'G-62Q8M0T3W6',
  );

}